In [14]:
import cv2
import numpy as np
i=cv2.imread(r"R:\stock.jpg")
i=cv2.resize(i,(500,500))
g=cv2.cvtColor(i,cv2.COLOR_BGR2GRAY)
g=np.float32(g)
res=cv2.cornerHarris(g,3,3,0.04)#source,blocksize,kernel size,number of points
res=cv2.dilate(res,None)# reduce extra points
print(res)
i[res>0.1*res.max()]=[0,255,0]
cv2.imshow("apu",i)
cv2.waitKey()
cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
import cv2
import numpy as np
i=cv2.imread(r"R:\getty_517194189_373099.webp")
i=cv2.resize(i,(500,500))
g=cv2.cvtColor(i,cv2.COLOR_BGR2GRAY)
g=np.float32(g)
res=cv2.cornerHarris(g,8,3,0.04)#source,blocksize,kernel size,number of points
#By changing the value of the blocksize the number of corner points can be reduced or increased
res=cv2.dilate(res,None)# reduce extra points
print(res)
i[res>0.1*res.max()]=[0,255,0]
cv2.imshow("apu",i)
cv2.waitKey()
cv2.destroyAllWindows()

[[-9.9999998e-03 -9.9999998e-03 -9.9999998e-03 ... -5.0625000e-02
  -5.0625000e-02 -5.0625000e-02]
 [ 6.6423034e-03  6.6423034e-03  6.6423034e-03 ...  6.6162109e-02
   6.6162109e-02  6.6162109e-02]
 [ 1.9541778e-02  1.9541778e-02  1.9541778e-02 ...  1.9353272e-01
   1.8652344e-01  1.8652344e-01]
 ...
 [ 2.8960565e+02  2.8960565e+02  2.8960565e+02 ...  2.8330749e-01
   3.6546266e-01  3.6546266e-01]
 [ 3.2612909e+02  3.2612909e+02  3.2612909e+02 ...  3.1047058e-01
   3.7937683e-01  3.7937683e-01]
 [ 3.2612909e+02  3.2612909e+02  3.2612909e+02 ...  3.1047058e-01
   3.7937683e-01  3.7937683e-01]]
